# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/faststripe',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/faststripe',
                'lib_path': 'faststripe'},
  'syms': {'faststripe.core': {}}}
