"""Async Stripe API client generated from Stripe's OpenAPI spec, with object conversion, pagination helpers, and webhook verification.

Docs: https://AnswerDotAI.github.io/faststripe/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_core.ipynb.

# %% auto #0
__all__ = ['sspec', 'pspec', 'obj_typs', 'stripe_group', 'StripeError', 'StripeSignatureError', 'camel', 'StripeObject', 's2obj',
           'StripeTransport', 'StripeApi', 'paged', 'pages', 'verify_webhook', 'StripeListener', 'stripe_listen',
           'stripe_trigger']

# %% ../nbs/01_core.ipynb #039eaef3
from fastcore.net import *
from fastcore.utils import *
from collections import deque
from fastspec.spec import SpecParser
from fastspec.oapi import OpenAPIClient, OpFunc
from fasttransport.core import AsyncTransport
from fastcore.apisurface import mk_groups
from .stripe_spec import sspec

import json,hmac,hashlib,time,re,httpx2,asyncio

# %% ../nbs/01_core.ipynb #1db6b434
def stripe_group(oid, path, verb, ptags, optags):
    return [s[1:-1] if s.startswith('{') and s.endswith('}') else s for s in path.strip('/').split('/')], verb

sspec = dict2obj(sspec)
pspec = SpecParser.from_openapi(sspec, stripe_group)

# %% ../nbs/01_core.ipynb #07a9c24c
class StripeError(Exception):
    def __init__(self, e):
        self.status_code = e.response.status_code
        try: self.err = e.response.json().get('error', {})
        except Exception: self.err = {}
        self.msg = self.err.get('message', str(e))
        self.param = self.err.get('param')
        self.type = self.err.get('type')
        super().__init__(self.msg)

    def __str__(self):
        s = f"StripeError({self.status_code}): {self.msg}"
        if self.param: s += f" [param: {self.param}]"
        return s

class StripeSignatureError(Exception): pass

# %% ../nbs/01_core.ipynb #ef6de504
def camel(s): return s.replace('.','_').replace('_',' ').title().replace(' ','')

class StripeObject(AttrDict):
    def __repr__(self): return f"{type(self).__name__}(id={self.get('id')})"

obj_typs = sorted({e for s in sspec['components']['schemas'].values()
                   for e in s.get('properties', {}).get('object', {}).get('enum', [])})
_objs = {o: type(camel(o), (StripeObject,), {}) for o in obj_typs}

def s2obj(x):
    if isinstance(x, list): return L(x).map(s2obj)
    if not isinstance(x, dict): return x
    o = x.get('object')
    d = AttrDict({k:s2obj(v) for k,v in x.items()})
    if not isinstance(o, str): return d
    res = _objs.get(o, StripeObject)(d)
    if o=='event' and 'data' in res and 'object' in res.data: res.data = res.data.object
    return res

# %% ../nbs/01_core.ipynb #5cc4142b
def _form_encoder(data, prefix=''):
    'Flatten a dictionary of data so that it can be used in a request body.'
    if not data: return {}
    result = {}
    for k,v in data.items():
        key = f'{prefix}[{k}]' if prefix else k
        if isinstance(v, dict): result.update(_form_encoder(v, key))
        elif isinstance(v, list): 
            for i,item in enumerate(v):
                if isinstance(item, dict): result.update(_form_encoder(item, f'{key}[{i}]'))
                else: result[f'{key}[{i}]'] = item
        else: result[key] = v
    return result

class StripeTransport(AsyncTransport):
    async def request(self, *args, raw=False, **kwargs):
        try: res = await super().request(*args, raw=raw, **kwargs)
        except httpx2.HTTPStatusError as e: raise StripeError(e) from None
        return res if raw else s2obj(res)

class StripeApi(OpenAPIClient):
    def __init__(self, api_key=None, webhook_key=None, publishable_key=None,
                 service_name='faststripe', headers=None, timeout=60.0):
        self.api_key = ifnone(api_key, os.getenv('STRIPE_SECRET_KEY', os.getenv('STRIPE_API_KEY')))
        self.webhook_key = ifnone(webhook_key, os.getenv('STRIPE_WEBHOOK_SECRET', os.getenv('STRIPE_WEBHOOK_KEY')))
        self.publishable_key = ifnone(publishable_key, os.getenv('STRIPE_PUBLISHABLE_KEY'))
        self.service_name = service_name
        self.headers = {'Authorization': f'Bearer {self.api_key}'}
        self.headers |= headers or {}
        self.transport = StripeTransport(timeout=timeout, base_headers=self.headers)
        self.ops = [OpFunc(o, self.transport, pspec.base_url, _form_encoder) for o in pspec.ops]
        self.func_dict = {f"{o.path}:{o.verb.upper()}": o for o in self.ops}
        self.groups = mk_groups(self.ops)
        for k,v in self.groups.items(): setattr(self, k, v)

# %% ../nbs/01_core.ipynb #a99be92c
async def paged(oper, *args, **kwargs):
    """Iterate through all pages of a Stripe API operation."""
    page = await oper(*args, **kwargs)
    yield page
    while page.has_more:
        last_id = page.data[-1].id
        page = await oper(*args, starting_after=last_id, **kwargs)
        yield page

# %% ../nbs/01_core.ipynb #5b2bae88
async def pages(oper, *args, **kwargs):
    "Retrieve all items from all pages of a Stripe API operation."
    return L([x async for page in paged(oper, *args, **kwargs) for x in page.data])

# %% ../nbs/01_core.ipynb #a5730b15
def verify_webhook(payload, sig_header, secret, tolerance=300):
    "Verify a Stripe webhook signature, accepting any of multiple v1 entries"
    if hasattr(payload, 'decode'): payload = payload.decode('utf-8')
    parts = [p.split('=', 1) for p in sig_header.split(',')]
    if any(len(p) != 2 for p in parts): raise StripeSignatureError('Unable to parse signature header')
    t = next((v for k,v in parts if k=='t'), None)
    v1s = [v for k,v in parts if k=='v1']
    if not t or not v1s: raise StripeSignatureError('No v1 signature found in header')
    exp = hmac.new(secret.encode(), f'{t}.{payload}'.encode(), hashlib.sha256).hexdigest()
    if not any(hmac.compare_digest(exp, v) for v in v1s): raise StripeSignatureError('Signature mismatch')
    try: age = time.time() - int(t)
    except Exception: raise StripeSignatureError('Invalid timestamp')
    if age > tolerance: raise StripeSignatureError('Timestamp outside tolerance zone')
    return True

# %% ../nbs/01_core.ipynb #4ab2d40f
class StripeListener:
    "A `stripe listen` process forwarding webhooks to `url`; `close` stops it when this object started it"
    def __init__(self, url, proc=None, secret=None):
        store_attr()
        self.log = deque(maxlen=200)
    def close(self):
        if self.proc and self.proc.returncode is None: self.proc.terminate()
    def __repr__(self): return f'StripeListener({self.url!r}, secret={self.secret and self.secret[:9]+"…"!r})'


# %% ../nbs/01_core.ipynb #2ba7ffaf
def _listening(url):
    "Whether some `stripe listen` process already forwards to `url`"
    import psutil
    return any(url in c and 'listen' in c and Path(c[0]).stem == 'stripe' for p in psutil.process_iter(['cmdline']) if (c := p.info['cmdline']))

async def stripe_listen(
    url, # Where the CLI forwards events, e.g. `http://localhost:8000/webhook`
    api_key=None, # Stripe secret key for the CLI; `STRIPE_SECRET_KEY` if None, and the CLI's own login when that is unset too
    timeout=30, # Seconds to wait for the CLI to report ready
):
    "Start `stripe listen --forward-to url` unless one is already running, and wait for the CLI to report ready"
    if _listening(url): return StripeListener(url)
    api_key = ifnone(api_key, os.getenv('STRIPE_SECRET_KEY'))
    args = ['listen', '--forward-to', url] + (['--api-key', api_key] if api_key else [])
    proc = await asyncio.create_subprocess_exec('stripe', *args, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.STDOUT)
    res = StripeListener(url, proc)
    async def _ready():
        async for line in proc.stdout:
            res.log.append(line := line.decode().rstrip())
            if 'Ready!' in line: return line
    try: line = await asyncio.wait_for(_ready(), timeout)
    except TimeoutError:
        res.close()
        raise TimeoutError(f'stripe listen did not report ready in {timeout}s:\n' + '\n'.join(res.log)) from None
    if not line: raise RuntimeError('stripe listen exited:\n' + '\n'.join(res.log))
    res.secret = first(re.findall(r'whsec_\w+', line))
    asyncio.create_task(_drain(proc, res.log))
    return res

async def _drain(proc, log):
    "Keep reading the CLI's output so a full pipe never blocks it"
    async for line in proc.stdout: log.append(line.decode().rstrip())

# %% ../nbs/01_core.ipynb #6cc5f534
async def stripe_trigger(
    event, # Event type the CLI should fake, e.g. `payment_intent.succeeded`
    overrides=None, # Fixture fields to set, e.g. `{'payment_intent:amount': 1000}`
    api_key=None, # Stripe secret key for the CLI; `STRIPE_SECRET_KEY` if None, and the CLI's own login when that is unset too
):
    "Run `stripe trigger event`, returning the CLI's output once the event has been sent"
    api_key = ifnone(api_key, os.getenv('STRIPE_SECRET_KEY'))
    args = ['trigger', event] + (['--api-key', api_key] if api_key else []) + [a for k,v in (overrides or {}).items() for a in ('--override', f'{k}={v}')]
    proc = await asyncio.create_subprocess_exec('stripe', *args, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.STDOUT)
    out = (await proc.communicate())[0].decode()
    if proc.returncode: raise RuntimeError(f'stripe trigger failed:\n{out}')
    return out

# %% ../nbs/01_core.ipynb #0070850f
@patch
async def parse_webhook(self:StripeApi, req):
    verify_webhook(evt:=await req.body(), req.headers.get('stripe-signature'), self.webhook_key)
    return s2obj(json.loads(evt))

# %% ../nbs/01_core.ipynb #af1cebac
def _metadata(evt):
    "Return metadata used for service routing from a Stripe event or object."
    obj = getattr(evt, 'data', evt)
    return getattr(obj, 'metadata', None) or getattr(evt, 'metadata', None) or {}

@patch
def filter_evt(self:StripeApi, evt):
    "Return True if `evt` belongs to this StripeApi service."
    if not self.service_name: return True
    return _metadata(evt).get("STRIPE_SERVICE_NAME") == self.service_name

