"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['stripe_openapi_url', 'stripe_spec']

# %% ../nbs/00_core.ipynb 2
from fastcore.all import *
from httpx import get as xget, post as xpost, delete as xdelete

import json, os

# %% ../nbs/00_core.ipynb 3
stripe_openapi_url = 'https://raw.githubusercontent.com/stripe/openapi/refs/heads/master/openapi/spec3.json'
stripe_spec = xget(stripe_openapi_url).json()
