# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_spec.ipynb.

# %% auto #0
__all__ = ['oapi_url', 'update_version']

# %% ../nbs/00_spec.ipynb #4ea88bd2
from fastcore.net import *
from fastcore.utils import *
from nbdev.config import set_version, get_config

import os, pprint, re

# %% ../nbs/00_spec.ipynb #45d23543
oapi_url = 'https://raw.githubusercontent.com/stripe/openapi/refs/heads/master/latest/openapi.spec3.json'

def update_version():
    'Update the version to the latest version of the Stripe API and the endpoints file.'
    sspec = urlsend(oapi_url, 'GET', return_json=True)
    stripe_version = sspec['info']['version'].split('.')[0].replace('-', '.')

    cfg = get_config()
    if cfg.version.rsplit('.', 1)[0] == stripe_version: return
    set_version(cfg.lib_path, stripe_version + '.0')
    txt = f"sspec = {pprint.pformat(sspec, width=360, sort_dicts=False)}\n"
    compile(txt, "faststripe/stripe_spec.py", "exec")
    (cfg.config_path/'faststripe/stripe_spec.py').write_text(txt)
    print(f"Updated version to {get_config().version}")
